feat: post activity service
Vogarify/vestibular-api pull request #26
Opened 2023-12-15 19:58 UTC by DanielMurta

## Changes
- [x] Create the service POST /v1/activity.
- [x] Create shared schema ActivitySchema.
- [x] Create feature schema ActivityPostBody.
- [x] Create a procedure to insert the Activity and check the question answer correctness..

2023-12-15 20:40 UTC, saitodeveloper commented on src/routes/activity/repository.js
> +    const { idAlternative, user_id, device_id, device_serial, idQuestion,  } = activity
The activity object doesn't have the device_id, device_serial properties, these will be on a `auth` object. Remember the **"Node world we'll use camelcase"**

2023-12-15 20:46 UTC, saitodeveloper commented on src/routes/activity/repository.js
> +const insertActivity = async (activity) => {
This activity doesn't contains the auth data on this part. You can expect the auth object here
```suggestion
const insertActivity = async (activity, auth) => {
```

2023-12-15 20:47 UTC, saitodeveloper commented on src/routes/activity/repository.js
> +    const { idAlternative, user_id, device_id, device_serial, idQuestion,  } = activity
Here you can divide the destruction operator.
```suggestion
    const { idAlternative, dQuestio,  } = activity
    const { userId, deviceSerial, deviceId } = auth
```

2023-12-15 20:49 UTC, saitodeveloper commented on src/routes/activity/service.js
> +    return await repository.insertActivity(activity)
You can hardcode the auth object for now, since we don't have the OAuth middleware ready.
```suggestion
    // TODO: change the auth from context
    const auth = { userId: 1, deviceId: 1, deviceSerial: 'some_serial' }
    return await repository.insertActivity(activity, auth)
```

2023-12-15 20:50 UTC, saitodeveloper commented on src/routes/activity/repository.js
> +    console.log(result)
You can remove the console.log

2023-12-15 20:51 UTC, saitodeveloper commented on src/routes/activity/repository.js
> +    return result
Result is a array you might want to return the last query executed on the procedure
```suggestion
    return result?.at(0)?.at(0)
```

2023-12-15 20:52 UTC, saitodeveloper requested changes
The changes are good, just some grooming to be done

2023-12-15 20:54 UTC, saitodeveloper commented
@DanielMurta, one last thing, you can install prettier extension on Visual Studi, ESlist extension and setup the configuration to save and format the file. I might create a doc as a tutorial.

2023-12-15 21:50 UTC, saitodeveloper commented on migrations.sqls/20231215004856-create-procedure-insert-activity.up.sql
> +
Just leave one break line at EOF

2023-12-15 22:04 UTC, DanielMurta commented
Changes done

2023-12-16 19:30 UTC, saitodeveloper approved these changes
LGTM

2023-12-16 19:31 UTC, merged